### ISSUE TITLE
Missing dependency on yaml extra in cafeteria?

### ISSUE THREAD

**Issue by alicederyn** [abn/cafeteria-asyncio#200] opened 2024-03-05 13:50 UTC
I'm seeing the following issue importing cafeteria-asyncio:

```text
  File "cafeteria/asyncio/callbacks.py", line 19, in <module>
    from cafeteria.logging import LoggedObject
  File "cafeteria/logging/__init__.py", line 6, in <module>
    from yaml import safe_load as load
ModuleNotFoundError: No module named 'yaml'
```

I have cafeteria-asyncio v0.3.0 and cafeteria v0.22.2 installed. I see [the following extra in cafeteria](https://github.com/abn/cafeteria/blob/e9f2b2a95f0ae022cbf39d72569fadd8f383e122/pyproject.toml#L39-L41):
```toml
[tool.poetry.extras]
# PyYAML is only required when YAML logging configuration is used.
yaml = ["PyYAML"]
```

I assume the fix is to depend on `cafeteria[yaml]`?

**Comment by abn** [comment] 2024-03-05 17:18
The code snippet you posted seems to be from an older cafeteria version. The yaml import now is optional.

https://github.com/abn/cafeteria/blob/62141356b0c4b5e3c8e8b7cad48ee13a2a9ad96d/src/cafeteria/logging/__init__.py#L30-L56

Maybe try reinstalling the environment?

**Comment by alicederyn** [comment] 2024-03-05 19:08
It's from the latest tag, https://github.com/abn/cafeteria/blob/v0.22.2/cafeteria/logging/__init__.py#L8

Maybe they haven't published since fixing it

**Comment by abn** [comment] 2024-03-05 19:45
Ah. Good catch. The issue is now fixed in https://pypi.org/project/cafeteria/0.22.3/.

If you are curious the fix was https://github.com/abn/cafeteria/commit/607864e91e26e55101794d125b187044c1cedf01.

In your environment, you can simply add a direct dependency on `PyYAML` or update environment to consume `cafeteria==0.22.3`.

**Closed as completed by abn** 2024-03-05 19:45 UTC
